language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  firefox: 45.8.0esr
env:
  - PLONE_VERSION=4.3 TEST_EGGS=collective.cover[test]
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.0
  fast_finish: true
install:
  - sed -ie "s#4.3.x.cfg#$PLONE_VERSION.x.cfg#" buildout.cfg
  - python bootstrap.py
  - bin/buildout buildout:test-eggs=$TEST_EGGS annotate
  - bin/buildout buildout:test-eggs=$TEST_EGGS
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage --output-dir=htmlcov -t "--layer=!Robot"
  - pip install --upgrade coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#simplesconsultoria
