services:
  - xvfb
language: python
python: 2.7
cache:
  directories:
    - $HOME/.pylint.d
    - eggs
    - parts/node
    - geckodriver
addons:
  firefox: "81.0"
env:
  - PLONE_VERSION=4.3 TEST_EGGS=collective.cover[test]
  - PLONE_VERSION=5.1
matrix:
  fast_finish: true
install:
  - sed -ie "s#4.3.x.cfg#$PLONE_VERSION.x.cfg#" buildout.cfg
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout buildout:test-eggs=$TEST_EGGS annotate
  - bin/buildout buildout:test-eggs=$TEST_EGGS
before_script:
  - >
    if [ ! -f geckodriver/geckodriver ]; then
      GECKODRIVER_VERSION=0.27.0
      wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
      tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver
    fi;
  - export PATH=$PATH:$PWD/geckodriver
  - firefox -v
script:
- bin/code-analysis
- bin/test
- bin/pylint --py3k --disable=no-absolute-import src/sc/embedder || true
after_success:
- pip install coverage
- coverage run bin/test --layer=\!Robot
# Coveralls
- pip install coveralls
- coveralls
# Codacy
- coverage xml
- pip install codacy-coverage
- python-codacy-coverage -r coverage.xml
notifications:
  irc: irc.freenode.org#simplesconsultoria
